version: "3" # version of compose format

services:
  nexttune-api:
    build: ./api # path is relative to docker-compose.yml localtion
    volumes:
      - ./api:/usr/src/api # mount point
    environment:
      - SENTRY_DNS
      - FLASK_ENV
    ports:
      - 5000:5000 # host:container

  nexttune:
    env_file: ./webapp/.env
    environment:
      - SPOTIFY_CALLBACK
      - SPOTIFY_SCOPE
      - SPOTIFY_APP_CLI_ID
      - SPOTIFY_APP_CLI_SEC
      - APP_KEY
    ports:
      - 8000:8000
