version: "3" # version of compose format

services:
  nexttune:
    build:
      dockerfile: ./webapp/Dockerfile
      context: .
    volumes:
      - ./webapp:/code
    environment:
      - SPOTIFY_CALLBACK
      - SPOTIFY_SCOPE
      - SPOTIFY_APP_CLI_ID
      - SPOTIFY_APP_CLI_SEC
      - APP_KEY
      - HOSTS
      - DEBUG
    ports:
      - 8000:8000
