version: 2
jobs:
  build:
    environment:
      - IMAGE_NAME: kleinkauff/webapp
    working_directory: ~/builddir
    docker:
      - image: circleci/python:3.6.4 # primary container for the build job
    steps:
      - checkout
      - setup_remote_docker
