version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kleinkauff/nexttune-webapp
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest -f webapp/Dockerfile .

  publish-dockerhub:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Publish image to Docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-dockerhub:
          requires:
            - build
          filters:
            branches:
              only: master
