version: 2
jobs:
  build:
    environment:
      - IMAGE_NAME: kleinkauff/webapp
    working_directory: ~/builddir
    docker:
      - image: circleci/python:3.6.4 # primary container for the build job
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest -f webapp/Dockerfile .

  publish-dockerhub:
    environment:
      - IMAGE_NAME: webapp
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish image to Docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
