version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kleinkauff/nexttune-webapp
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest -f webapp/Dockerfile .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-dockerhub:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish image to Docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy-digital-ocean:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "4e:66:00:f6:11:02:a3:62:2e:8d:6c:18:b4:a6:57:76"
      - run:
          name: Deploy app to Digital Ocean
          command: |
            ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP "cd /var/www/nexttune && make pull-and-deploy-prod"

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-dockerhub:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-digital-ocean:
          requires:
            - publish-dockerhub
          filters:
            branches:
              only: master
